name: sh_util toc
on:
  push:
    branches: [ master ]
    paths:
      - '**.md'
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v2
